version: "3.9"
services:
    app:
        build: .
        ports:
            - "8000:8000"
        image: vendas:django
        command: python Vendas/manage.py runserver 0.0.0.0:8000 
        depends_on:
            - db
    db:
        container_name: mysqldb
        restart: always        
        image: mysql:8.0
        ports:
            - "3307:3307"
        environment:
            MYSQL_DB: sqldb
            MYSQL_ROOT_PASSWORD: root
            'HOST': 'sqldb'
            extra_hosts:
                "host.docker.internal:host-gateway"