version: "3.9"
services:
    app:
        build: .
        ports:
            - "8000:8000"
        image: vendas:django
        command: bash -c "python Vendas/manage.py makemigrations && python Vendas/manage.py migrate && python Vendas/manage.py runserver 0.0.0.0:8000"
        volumes:
            - ./:/app
        depends_on:
            - mysqldb
    mysqldb:
        image: mysql:8.0
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: 'appdb'
            MYSQL_PASSWORD: 'root'
            MYSQL_ROOT_PASSWORD: 'root'
        volumes:
            - ./mysql-data:/var/lib/mysql